(function(b){var k=b.UI=b.UI||{},g=k.Sub=k.Sub||{};b.modules["UI.Sub"]=!0;g.__init__=function(u){delete g.__init__;b.load("UI.Tmpl",function(){var h=b.$,l=b.$window,m=b.$main,n=k.Tmpl;g=k.Sub=function(a){if(!(this instanceof g))return new g(a);a=a||{};n.prototype.constructor.call(this,a);this.playing=!0;this.since=this.sub=null;this.seen={};this.$sections=[];this.showing=0;this.$articles=[];this.queue=a.queue||[];return this};g.prototype=Object.create(n.prototype);var r=function(){this.queue.length?
this.$waiting.hide():this.$waiting.fadeIn(300);if(this.playing){var a=this.queue.pop();if(a){var c=h('<article style="display: none" data-id="'+a.id+'" data-ts="'+a.created+'"><span class="kon-ts">'+b.ago(a.created)+'</span><h2><a href="'+a.url+'">'+a.title+'</a></h2><p>posted by <a href="'+b.urls.reddit+"u/"+a.author+'">'+a.author+'</a> in <a href="'+b.urls.www+"r/"+a.sub+'">/r/'+a.sub+'</a></p><p class="kon-image"><a href="'+a.url+'"><img src="'+a.url+'"></a></p><p><a href="'+b.urls.reddit+"r/"+
a.sub+"/comments/"+a.id+'">comments</a></p></article>'),d=h('<span class="kon-votes" data-vote="none">'),e=h('<button class="kon-upvote">'),f=h('<button class="kon-downvote">');d.append(e);d.append(f);c.prepend(d);e.click(function(c){if(b.loggedIn)return"up"===d.data("vote")?(d.data("vote","none"),e.removeClass("kon-voted"),b.request("post/vote",{sid:b.sid,id:a.id,dir:0})):(d.data("vote","up"),e.addClass("kon-voted"),b.request("post/vote",{sid:b.sid,id:a.id,dir:1})),f.removeClass("kon-voted"),c.preventDefault&&
c.preventDefault(),!1;b.login()});f.click(function(c){if(b.loggedIn)return"down"===d.data("vote")?(d.data("vote","none"),f.removeClass("kon-voted"),b.request("post/vote",{sid:b.sid,id:a.id,dir:0})):(d.data("vote","down"),f.addClass("kon-voted"),b.request("post/vote",{sid:b.sid,id:a.id,dir:-1})),e.removeClass("kon-voted"),c.preventDefault&&c.preventDefault(),!1;b.login()});this.$sections[this.showing%this.$sections.length].prepend(c);setTimeout(function(){var a=p(l.width());++this.showing<=a&&(a=305*
this.showing+5+"px",b.$header.children(".kon-wrapper").css("max-width",a),m.css("max-width",a));c.fadeIn(300)}.bind(this),500);this.$articles.unshift(c);if(60<this.$articles.length){var q=this.$articles.pop();q.fadeOut(300,function(){q.remove()})}}}},v=function(){for(var a=0;a<this.$articles.length;++a){var c=this.$articles[a];c.children(".kon-ts").text(b.ago(c.data("ts")))}},w=function(){var a={sub:this.sub};this.since&&(a.since=this.since);b.request("post/list",a,function(a){if(200===a.status.code){a=
a.result.posts;for(var b=a.length-1;-1<b;--b){var e=a[b];this.seen[e.id]||(this.seen[e.id]=!0,this.since=e.id,this.queue.unshift(e),100<this.queue.length&&(this.queue=this.queue.slice(0,99)))}}}.bind(this))},p=function(a){a=Math.floor((a-5)/305);1>a?a=1:6<a&&(a=6);return a},s=function(a){a=p(a);if(a!==this.$sections.length){m.empty();this.$sections=[];for(var c=0;c<a;++c){var d=h("<section>");this.$sections.push(d);m.append(d)}(d=this.$articles.length)?d<a&&(a=d):a=1;a=305*a+5+"px";b.$header.children(".kon-wrapper").css("max-width",
a);m.css("max-width",a);for(c=0;c<d;++c)this.$sections[c%this.$sections.length].append(this.$articles[c])}},t=function(){this.$waiting=h('<p style="display: none">Waiting for more posts...</p>');b.$messages.append(this.$waiting);r.call(this);setInterval(r.bind(this),5E3);setInterval(w.bind(this),3E4);setInterval(v.bind(this),15E3)};g.prototype.render=function(){n.prototype.render.call(this);b.$body.addClass("kon-sub");this.sub=b.$body.data("sub")||"all";this.$play=h('<button class="kon-pause"><hr><hr></button>');
this.$play.click(function(){this.playing?(this.playing=!1,this.$play.removeClass("kon-pause"),this.$play.addClass("kon-play")):(this.playing=!0,this.$play.removeClass("kon-play"),this.$play.addClass("kon-pause"))}.bind(this));b.$header.children(".kon-wrapper").prepend(this.$play);var a=this.queue.length;if(a){this.since=this.queue[0].id;for(var c=0;c<a;++c)this.seen[this.queue[c].id]=!0}var d,e=l.width();s.call(this,e);l.resize(function(){var a=l.width();e!==a&&(e=a,clearTimeout(d),d=setTimeout(s.bind(this,
a),300))}.bind(this));var f=this;b.request("user/get",{sid:b.sid},function(a){200===a.status.code&&a.result&&a.result.session&&!a.result.session.nsfw?b.load("UI.Dialog",function(){b.UI.Dialog({title:"Knights of New",content:"<p>Welcome to Knights of New. This site is a live feed of posts from reddit. Some posts are Not Safe For Work. Are you over the age of 18?</p>",width:300,height:110,buttons:[{text:"No. I want to leave.",onclick:function(){window.location.href="http://www.mphennum.com/"}},{text:"Yes. Please let me in!",
onclick:function(){this.hide();t.call(f);b.request("user/over18",{sid:b.sid})}}]}).show()}):t.call(f)});return this};u()})}})(window.KON);
